// Context-guardrail builders — the LIVE fix for the report's biggest line item. The
// missed-/compact failure mode is not knowing you crossed the threshold; a statusline
// script that reads Claude Code's context_window JSON warns in the moment instead.
// Everything here is pure string-building + a settings.json READ — never a write to
// ~/.claude (runFix emits reviewable artifacts under ./.cc-audit/, per the fix contract).
//
// The threshold is a PERCENTAGE of the model's context window (not the report's absolute
// 160K line) so the same script is right on a 200K and a 1M window. It's a shell variable
// at the top of the generated script — the calibrated "personal quality knee" work can
// feed it later without changing the plumbing.

import { readFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { join } from 'node:path';

export const GUARD_SCRIPT_NAME = 'cc-audit-context-guard.sh';
export const DEFAULT_WARN_PCT = 80;
export const DEFAULT_RED_PCT = 90;

export interface UserSettings {
  /** The real settings file the proposal targets. */
  path: string;
  /** File contents, or null when the file doesn't exist / isn't readable. */
  raw: string | null;
  /** Parsed object, or null when missing OR corrupt (raw non-null ⇒ corrupt JSON). */
  parsed: Record<string, unknown> | null;
}

export function readUserSettings(): UserSettings {
  const path = join(homedir(), '.claude', 'settings.json');
  let raw: string | null = null;
  try {
    raw = readFileSync(path, 'utf8');
  } catch {
    return { path, raw: null, parsed: null };
  }
  try {
    const parsed: unknown = JSON.parse(raw);
    return { path, raw, parsed: parsed && typeof parsed === 'object' ? (parsed as Record<string, unknown>) : null };
  } catch {
    return { path, raw, parsed: null };
  }
}

/** The user's current statusLine command, when one is configured. */
export function existingStatusLineCommand(parsed: Record<string, unknown> | null): string | null {
  const sl = parsed?.statusLine;
  if (!sl || typeof sl !== 'object') return null;
  const { type, command } = sl as Record<string, unknown>;
  return type === 'command' && typeof command === 'string' && command.trim() ? command : null;
}

/**
 * The guardrail statusline script. Reads Claude Code's statusline JSON on stdin
 * (context_window.used_percentage, v2.1.132+; absent ⇒ degrades to no guard segment),
 * and in wrapper mode runs the user's existing statusline first — stdin is captured
 * once and re-piped, since it can't be consumed twice. No jq/node dependency: the
 * statusline runs in a minimal shell env, so extraction is POSIX grep.
 */
export function buildGuardScript(opts: { existingCommand: string | null; warnPct?: number; monthlyUsd: number }): string {
  const warn = opts.warnPct ?? DEFAULT_WARN_PCT;
  const red = Math.max(opts.warnPct ?? DEFAULT_WARN_PCT, DEFAULT_RED_PCT);
  const habit = `≈$${Math.max(1, Math.round(opts.monthlyUsd))}/mo habit`;
  const wrapperBlock = opts.existingCommand
    ? `\n# Your original statusline, unchanged (this script wraps it):\nbase=$(printf '%s' "$input" | ${opts.existingCommand})\n`
    : `\nbase=""\n`;
  return `#!/bin/bash
# cc-audit context guardrail — generated by \`cc-audit fix\`, yours to edit.
# Warns in the statusline when live context crosses the /compact threshold, so you
# compact proactively instead of hitting the auto-compact wall (${habit}).
# Thresholds are % of the context window (window-size agnostic — correct on 1M too):
WARN_PCT=${warn}
RED_PCT=${red}

input=$(cat)
${wrapperBlock}
# used_percentage from the statusline JSON (Claude Code v2.1.132+). Missing or
# non-numeric ⇒ no guard segment, never an error.
pct=$(printf '%s' "$input" | grep -o '"used_percentage"[[:space:]]*:[[:space:]]*[0-9.]*' | head -n1 | grep -o '[0-9.]*$')
pct=\${pct%%.*}
case "$pct" in '' | *[!0-9]*) pct='' ;; esac

guard=''
if [ -n "$pct" ]; then
  if [ "$pct" -ge "$RED_PCT" ]; then
    guard=$(printf '\\033[31mctx %s%% — /compact NOW (${habit})\\033[0m' "$pct")
  elif [ "$pct" -ge "$WARN_PCT" ]; then
    guard=$(printf '\\033[33mctx %s%% — /compact soon (${habit})\\033[0m' "$pct")
  else
    guard=$(printf '\\033[2mctx %s%%\\033[0m' "$pct")
  fi
fi

if [ -n "$base" ] && [ -n "$guard" ]; then
  printf '%s %s\\n' "$base" "$guard"
elif [ -n "$base" ]; then
  printf '%s\\n' "$base"
else
  printf '%s\\n' "$guard"
fi
exit 0
`;
}

/** The proposed settings.json: the user's settings verbatim with statusLine pointed at
 *  the installed guard script. `parsed` null (missing/corrupt file) ⇒ minimal object. */
export function buildSettingsProposal(parsed: Record<string, unknown> | null, scriptTargetPath: string): string {
  const next = { ...parsed, statusLine: { type: 'command', command: scriptTargetPath } };
  return `${JSON.stringify(next, null, 2)}\n`;
}
